# Generated by Django 4.2.28 on 2026-03-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notice_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
